controller_list:
  - name: fake_arm_1_controller
    joints:
      - base_footprint_joint
      - prismatic_link_to_revolute_link
      - revolute_link_to_base_link
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5